version: 2.1

commands:
  setup:
    steps:
      - checkout
      - restore-npm-cache
      - run: npm ci
      - save-npm-cache
  save-npm-cache:
    steps:
      - save_cache:
          key: v1-npm-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
  restore-npm-cache:
    steps:
      - restore_cache:
          key: v1-npm-{{ checksum "package-lock.json" }}

executors:
  node-browsers:
    docker:
      - image: circleci/node:latest-browsers
  git:
    docker:
      - image: tianon/github-hub:latest
orbs:

jobs:
  test-scrape:
    executor: node-browsers
    steps:
      - setup
      - run:
          name: scrape every configured job
          command: |
            git diff --name-only origin -- venues/*/config.js | \
              awk -F "/" '{ print $(NF - 1) }' |
              xargs -L 1 \
                npm run scrape --
  scrape:
    executor: node-browsers
    parameters:
      target:
        type: string
    steps:
      - setup
      - run: npm run scrape -- << parameters.target >>
      - persist_to_workspace:
          root: .
          paths:
            - venues/<< parameters.target>>/scraped.ltsv
  commit:
    executor: git
    parameters:
      target:
        type: string
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: cat venues/<< parameters.target>>/scraped.ltsv

workflows:
  # test:
  #   jobs:
  #     - test-scrape:
  #         filters:
  #           branches:
  #             ignore:
  #               - master
  scrape:
    jobs:
      - scrape:
          target: hikarie
          filters: # tmp
            branches:
              only:
                - scrape_on_circleci
      - scrape:
          name: scrape-kosugi-square
          target: kosugi-square
          filters: # tmp
            branches:
              only:
                - add_tokyu-square-musashikosugi
      - commit:
          target: kosugi-square
          requires:
            - scrape-kosugi-square
