version: 2.1

commands:
  scrape:
    parameters:
      target:
        description: target to scrape
        type: string
    steps:
      - run: node lib/cli.js scrape << parameters.target >>
      # - run: npm run scrape -- ${target} # after merged in master
executors:
  self:
    docker:
      - image: okitan/venue-scraper
    working_directory: /app
orbs:
  docker-publish: circleci/docker-publish@0.1.0
jobs:
  scrape:
    executor: self
    steps:
      - scrape

workflows:
  scrape:
    jobs:
      - scrape:
          target: hikarie
          filters: # tmp
            branches:
              only:
                - try_scrape_on_circleci
  build_and_publish_docker_image:
    jobs:
      - docker-publish/publish:
          image: okitan/venue-scraper
          filters:
            branches:
              only:
                - master
