version: 2.1

commands:
  setup:
    steps:
      - checkout
      - restore-npm-cache
      - run: npm ci
      - save-npm-cache
  save-npm-cache:
    steps:
      - save_cache:
          key: v1-npm-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
  restore-npm-cache:
    steps:
      - restore_cache:
          key: v1-npm-{{ checksum "package-lock.json" }}

executors:
  node:
    docker:
      - image: circleci/node:latest
    resource_class: small
  node-browsers:
    docker:
      - image: circleci/node:latest-browsers
orbs:

jobs:
  test:
    executor: node
    steps:
      - setup
      - run: npm test
  test-scrape:
    executor: node-browsers
    steps:
      - setup
      - run:
          name: scrape every configured job
          command: |
            git diff --name-only origin -- venues/*/config.js | \
              awk -F "/" '{ print $(NF - 1) }' |
              xargs --no-run-if-empty -L 1 \
                npm run scrape --

workflows:
  test:
    jobs:
      - test
      - test-scrape
