version: 2.1

commands:
  save-npm-cache:
    steps:
      - save_cache:
          key: v1-npm-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
  restore-npm-cache:
    steps:
      - restore_cache:
          key: v1-npm-{{ checksum "package-lock.json" }}

executors:
  self:
    docker:
      - image: okitan/venue-scraper:latest
    working_directory: /app
orbs:

jobs:
  test-scrape:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - restore-npm-cache
      - run: npm ci
      - save-npm-cache
      - run:
          name: scrape every configured job
          command: |
            git diff --name-only origin -- venues/*/config.js | \
              awk -F "/" '{ print $(NF - 1) }' |
              xargx -0 -n 1 \
                npm run scrape --
  scrape:
    executor: self
    parameters:
      target:
        type: string
    steps:
      - run: npm run scrape -- << parameters.target >>

workflows:
  test:
    jobs:
      - test-scrape:
          filters:
            branches:
              ignore:
                - master
  scrape:
    jobs:
      - scrape:
          target: hikarie
          filters: # tmp
            branches:
              only:
                - scrape_on_circleci
      # - scrape:
      #     target: kosugi-square
      #     filters: # tmp
      #       branches:
      #         only:
      #           - add_tokyu-square-musashikosugi
