name: check scrape pr

on:
  pull_request:
    paths: 
      - "**/scraped.ltsv"

jobs:
  check-scrape-pr:
    runs-on: ubuntu-latest

    steps:
      - name: check
        # on.pull_request.paths and changed_files == 1 means only scraped.ltsv is changed
        if: >
          github.event.pull_request.changed_files == 1 &&
          github.event.pull_request.additions <= 1 &&
          github.event.pull_request.deletions <= 1
        run: |
          echo "it seems normal update"
        

