name: check link pr

on:
  pull_request:
    paths: 
      - "**/notlinked.ltsv"

jobs:
  check-scrape-pr:
    runs-on: ubuntu-latest

    steps:
      - name: check auto merge
        # on.pull_request.paths and changed_files == 1 means only notlinked.ltsv is changed
        if: >
          github.event.pull_request.changed_files == 1 &&
          github.event.pull_request.additions == 0
        run: |
          curl -vv \
               -X PATCH \
               -H "Authorization: token ${{ secrets.MY_GITHUB_TOKEN }}" \
               -H 'Accept: application/vnd.github.v3+json' \
               "${{ github.event.pull_request._links.issue }}" \
               -d '{"labels": ["mergeable"]}'
