name: link

on:
  schedule:
    - cron: 0 9 * * * # 18:00 JST

jobs:
  scrape:
    strategy:
      matrix:
        venues:
          - scramble-square
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: switch to branch
        run: git checkout "link-${{ matrix.venues}}" || git checkout -b "link-${{ matrix.venues }}"
      - run: npm install
      - run: npm run link ${{ matrix.venues }}
        env:
          FOURSQUARE_TOKEN: ${{ secrets.FOURSQUARE_TOKEN }}
      - run: script/push_linked.sh ${{ matrix.venues }}
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
