name: auto merge

on:
  pull_request:
    types: [labeled]
    branches: 
      - master

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: merge
        uses: "pascalgn/automerge-action@7854d3bd607dccdaf0b2c134b699a812c8960213"
        env:
          GITHUB_TOKEN: "${{ secrets.MY_GITHUB_TOKEN }}"
          MERGE_LABELS: mergable
          MERGE_METHOD: squash
          MERGE_DELETE_BRANCH: true
          
