name: on branch pushed

on:
  push:
    branches:
      - link-*
      - scrape-*

jobs:
  make-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          pr_title: "update venue by ${{ github.ref }}"
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
