name: pr

on:
  push:
    branches:
      - link-*
      - scrape-*
      - commit-* # TODO: remove

jobs:
  pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1 # https://github.com/repo-sync/pull-request/issues/14
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          pr_title: "update venue by ${{ github.ref }}"
          github_token: ${{ secrets.GITHUB_TOKEN }}
