name: scrape

on:
  schedule:
    - cron: 0 0 * * * # 09:00 JST

jobs:
  scrape:
    strategy:
      matrix:
        venues:
          - fullel-jiyugaoka
          - grand-tree
          - hikarie
          - kosugi-square
          - lala-terrace
          - magnet
          - scramble-square
          - shibuya-stream
          - sweets-forest
          - tokyu-toyokoten
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: switch to branch
        run: git checkout "scrape-${{ matrix.venues }}" || git checkout -b "scrape-${{ matrix.venues }}"
      - run: npm install
      - run: npm run scrape ${{ matrix.venues }}
      - run: script/push_scraped.sh ${{ matrix.venues }}
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
