name: scrape

on:
  schedule:
    - cron: 0 1 * * * # 10:00 JST

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: docker://node:alpine
    - run: npm install
    - run: npm run scrape scramble-square
