name: scrape

on:
  schedule:
    - cron: 0 0 * * * # 09:00 JST

jobs:
  scrape:
    strategy:
      matrix:
        venues:
          - scramble-square
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker://node:alpine
      - run: npm install
      - run: npm run scrape {{ matrix.venues }}
