name: test

on:
  push:
    branches-ignore:
      - link-*
      - scrape-*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - run: npm ci
      - run: npm test
  test-scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # to git diff
      - run: git fetch origin master
      - name: install libgbm
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm-dev
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - run: npm ci
      - name: scrape changed
        run: |
          git diff --name-only origin/master -- venues/*/config.*s \
          | awk -F "/" '{ print $(NF - 1) }' \
          | xargs --no-run-if-empty -L 1 npm run scrape -- -t
        env:
          LANG: ja_JP.UTF-8
      - name: show changed file
        run: |
          git diff origin/master -- venues/*/scraped.ltsv
