name: test

on:
  push:
    branches-ignore:
      - link-*
      - scrape-*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - run: npm run build:check
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - run: npm test
  test-scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: install libgbm
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm-dev
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - name: scrape changed
        run: |
          git diff --name-only origin/master -- venues/*/config.*s \
          | awk -F "/" '{ print $(NF - 1) }' \
          | xargs --no-run-if-empty -L 1 npm run scrape -- -t
        env:
          LANG: ja_JP.UTF-8
      - name: show changed file
        run: |
          git diff origin/master -- venues/*/scraped.ltsv
